// Generated by CoffeeScript 1.7.1
var cities;

cities = require('./cities');

module.exports = {
  'cities': {
    get: cities.all,
    post: cities.create
  },
  'cities/:id': {
    "delete": cities.destroy
  }
};
